import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

const poppins = Poppins(
  {
    weight: ["100", "200", "400", "500", "600", "800"]
  }
)

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.className}h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <header className=" md:w-11/12 mx-auto">
          <Navbar></Navbar>
        </header>

        <main className=" md:w-11/12 mx-auto">
          {children}
        </main>


        <footer className="py-2 md:w-11/12 mx-auto">
          <Footer></Footer>
        </footer>

      </body>
    </html>
  );
}
